### ISSUE TITLE
Values go out of graph area

### ISSUE THREAD

**Issue by nurozcan** [swharden/Csharp-Data-Visualization#11]
Hello, I am working with 18-01-15_form_drawing project and trying to change y axis values with strings. I did and it looks normal until using zoom. when I zoom to axis my values go out the graph. When I scroll the bar, values  look in graph area. Could you please help mi? Thank you.
![vertical_axis_code](https://user-images.githubusercontent.com/32374289/85715840-881b7e00-b6f4-11ea-9ce6-19575f5df418.PNG)
![in_area](https://user-images.githubusercontent.com/32374289/85715890-949fd680-b6f4-11ea-9fe0-0d3d719c841c.PNG)
![out_of_zoom](https://user-images.githubusercontent.com/32374289/85715901-979ac700-b6f4-11ea-9761-1a645ea4d177.PNG)

**Comment by swharden** [comment]
Hey @nurozcan, my guess is you're not compensating for this offset.

![image](https://user-images.githubusercontent.com/4165489/85730983-1dece400-b6c8-11ea-89ba-1f15e6379434.png)

This number of pixels is `plt.GetSettings(false).dataOrigin.Y`

Also, you may be doing more work than is necessary drawing your own ticks and grid lines.
You could do something like:

```cs
double[] yPositions = { 1, 2, 3 };
string[] yPabels = { "XX", "YY", "AA" };
plt.YTicks(yPositions, yPabels);
```

See:
https://swharden.com/scottplot/cookbooks/4.0.36/#customize-ticks-define-tick-positions
