### ISSUE TITLE
How to, Detect sound Frequancy sample ( 10KHZ )

### ISSUE THREAD

**Issue by autoprog** [swharden/Csharp-Data-Visualization#14]
hi,
example  17-07-16_microphone running ok

how to, Detect sample especifique  frequency, example: 1000k, 5000k, or....11000, 18000khz

processing data  sample (10ms),  serarch in sample save buffer.

thanks,
Carlos.

**Comment by swharden** [comment]
Hi @autoprog, 

This project has evolved into a standalone library called FftSharp (which has its own NuGet package).

You will likely find what you need over there! Let me know if you still have trouble https://github.com/swharden/FftSharp 👍

**Comment by swharden** [comment]
```cs
double[] fftPower = FftSharp.Transform.FFTpower(audio);
double[] freqs = FftSharp.Transform.FFTfreq(sampleRate, fftPower.Length);
```

You can loop over power to find the index of peak power, then report the frequency at that index 🚀

**Comment by autoprog** [comment]
hi  swharden,
**thank you for your help.**

[ SOLVED ]
FftSharp (which has its own NuGet package) = ok

simple: int freqint = (int)peakFreq;

thanks,
Carlos.
