### ISSUE TITLE
What to use for Graphs visualization?

### ISSUE THREAD

**Issue by Oleg26Dev** [swharden/Csharp-Data-Visualization#15]
I mean something like NodeXL to visualize nodes set with connections etc

**Comment by swharden** [comment]
Hi @Oleg26Dev,

You mention NodeXL (https://www.smrfoundation.org/nodexl)

![image](https://user-images.githubusercontent.com/4165489/146686543-d929b264-00f4-492c-a2d5-fc15beca8477.png)

I'm not aware of a .NET tool designed for visualizing graphs. Googling a bit I found https://www.microsoft.com/en-us/research/project/microsoft-automatic-graph-layout/?from=http%3A%2F%2Fresearch.microsoft.com%2Fen-us%2Fprojects%2Fmsagl%2F and you may find that useful.

Admittedly determining an optimal layout is the hard part, but once that is achieved it is relatively straightforward to draw images and connecting lines using `System.Drawing` or `Microsoft.Maui.Graphics`

Hope it helps!
