### ISSUE TITLE
A few questions regarding FFT Frequency

### ISSUE THREAD

**Issue by vbisbest** [swharden/Csharp-Data-Visualization#2]
Thank you for your work on this project.  I am working on a project myself on Raspberry Pi using Windows IoT (ie. UWP).  Here are a few questions:
1. I imagine if the nuget packages exist for .Net Core, then your project should still work.  Any other thoughts on .Net Core?
2. Your frequency range seems to start in the mid range frequency.  For instance your voice is on the far left where it should perhaps be around the middle.  Low bass will not register as it is.  Thoughts on how to capture that?
3. Is there any way to apply windowing to your frequency example?  I am hoping that cleans up the frequency chart.  I see you do use windowing in the spectrograph example.
4. What are your thoughts on narrowing the number of frequencies.  I am looking to get only 8 "bands".  Think of a graphic eq with 8 frequncies.   I suppose one option is manually adding everything between two frequencies.  But hoping FFT would handle this.

Thank you for your input!

**Comment by swharden** [comment]
This repository has numerous frequency-related projects:
https://github.com/swharden/Csharp-Data-Visualization

For simplicity, I will focus on this one:
https://github.com/swharden/Csharp-Data-Visualization/tree/master/projects/17-07-16_microphone

1. Presumably, although I haven't spent much time on .Net core. It's a relatively simple math process (the FFT) which is used in lots of tasks, so I imagine it's easy to get going in .Net core even if it requires a different library.
2. frequency range goes down to 0, and low bass will register
3. windowing is useful, and is applied. The window is applied here https://github.com/swharden/Csharp-Data-Visualization/blob/e76559ca66f55f210926d8d024179ce43b92c16f/projects/18-01-11_microphone_spectrograph/WindowsFormsApp1/WindowsFormsApp1/Form1.cs#L114
4. To narrow the number of frequencies, decrease the number of values you feed to the FFT function. You will always get 1/2 the number of values out of the FFT as you put in. Alternatively, you could get more frequencies out than you need and then bin and average them.

PS: you may find this useful:
https://github.com/swharden/Csharp-Data-Visualization/blob/master/notes/FFT.md

Best!
Scott
