### ISSUE TITLE
FFt audiomonitor output hangs after a few minutes, or skips

### ISSUE THREAD

**Issue by tristankamp** [swharden/Csharp-Data-Visualization#35]
Hello, i built a huge music visualizer on top of your FFT Graph, only to find it breaks pretty consistenly.

Solution was simple, but took me 5 days.

Divide the sample rate down to 10 milliseconds, just like the waveform monitor. 

Its the only way

**Comment by swharden** [comment]
> it breaks pretty consistenly

Thanks for reporting this @tristankamp! I haven't experienced this issue, so I can't offer much advice about how to resolve it. Can you provide a minimal code sample that allows me to recreate this problem?

Thanks!
Scott

**Comment by swharden** [comment]
Also, note that the FftSharp page has a microphone demo.

https://github.com/swharden/FftSharp#microphone-demo

Perhaps the strategy demonstrated there will work better for your needs?

![](https://github.com/swharden/FftSharp/blob/main/dev/microphone-fft.gif?raw=true)

**Comment by swharden** [comment]
Also you may find https://swharden.com/csdv/audio/fft/ helpful

![](https://swharden.com/csdv/audio/fft/fft-csharp-audio-microphone.gif)

**Comment by tristankamp** [comment]
if you just take the original code, unmodified, play some songs on youtube,
and skip while music is playing, the graph "freezes" instead of going to
zero. When music then is resumed, the new graph dances on top of the frozen
one, values added.


Den søn. 14. maj 2023 kl. 22.43 skrev Scott W Harden <
***@***.***>:

**Comment by tristankamp** [comment]
it might be because i have a usb headset

Den man. 15. maj 2023 kl. 08.48 skrev Tristan Kamp ***@***.***>:
