### ISSUE TITLE
PCM audio input clips

### ISSUE THREAD

**Issue by swharden** [swharden/Csharp-Data-Visualization#5]
On a different computer I noticed this project clips (it seems the input is exactly 2x too large):
https://github.com/swharden/Csharp-Data-Visualization/tree/master/projects/18-09-19_microphone_FFT_revisited

### Song at 100% volume
![image](https://user-images.githubusercontent.com/4165489/47295511-cbe3e900-d5dd-11e8-9933-d93a9c5a75e9.png)

### Same song at 50% volume
![image](https://user-images.githubusercontent.com/4165489/47295462-b078de00-d5dd-11e8-9e03-8af7e3f0bd30.png)

**Comment by Tiuipuv** [comment]
I just ran the compiled version of the FFT AudioMonitor, and it presented the same issue. If I yell into the mic, it has far less 'mic noise' than the times that I open the program in silence.

**Comment by swharden** [comment]
One thought I had is that I'm trying to force the sound card to operate in 16-bit mode, but perhaps not all sound cards are happy with this. I made an alternate version which auto-detects the bit rate the sound card wants to operate at. Does this version have the same problem? [autoBitRate.zip](https://github.com/swharden/Csharp-Data-Visualization/files/2834468/autoBitRate.zip)

I'm starting to wonder if it may be an issue with NAudio (the library I'm using to access the microphone). They have demo code on their website you could use to test it out if you want...
https://github.com/naudio/NAudio/blob/master/Docs/RecordWavFileWinFormsWaveIn.md

ps: Thanks for helping me debug this! I can't recreate the issue on my home computer (but I can at my work computer).

**Comment by swharden** [comment]
I'm so sorry - I sent you the wrong ZIP. Does this version have the same problem?

[autoBitrateCircular.zip](https://github.com/swharden/Csharp-Data-Visualization/files/2834473/autoBitrateCircular.zip)

**Comment by swharden** [comment]
I know what the problem is. I way over-thought it!

* left-click-drag to pan
* right-click-drag to zoom
* middle-click once to auto-scale

Just zoom out! It auto-zooms based upon the peak volume it hears in the first half-second or so.

Let me know how that works for you!

**Comment by Tiuipuv** [comment]
Haha yeah, sorry... I should have noticed the units were off. Speaking of which, your y-axis is labeled Hz, but it is definitely not 1 Hz up there. Does it maybe mean kHz? or are the graph units arbitrary...

**Comment by swharden** [comment]
Glad you got it working!

Yeah, that was a typo in the axis label. Those units are kHz. You can test it with http://www.szynalski.com/tone-generator/ to be sure.
