### ISSUE TITLE
Does this work with ASIO? 

### ISSUE THREAD

**Issue by Edris89** [swharden/Csharp-Data-Visualization#6]
Hi there,

I am making a hardware device that has a rgb ledstrip connected to it. 
I wanted to react the ledstrip on the music. But I also wan't it to work with ASIO. 
Because there are a lot of music producers that are in need of a reactive sound rgb ledstrip that work with fl studio or another daw. Most of them are using ASIO.

Is this possible?

**Comment by swharden** [comment]
I haven't tried it with ASIO, so I'm not sure! Currently all sound card projects interact with audio using nAudio (https://github.com/naudio/NAudio). If you create a variant that works with ASIO, or confirm these projects work with ASIO, let us know!

Thanks
Scott
