### ISSUE TITLE
How can I 2d-FFT fo Image using this NAudio.FFT?

### ISSUE THREAD

**Issue by bemoregt** [swharden/Csharp-Data-Visualization#8]
Hi, @swharden 

How can I 2d-FFT fo Image using this NAudio.FFT?

Please show me the example code.

Thanks in advance.

from @bemoregt.

**Comment by swharden** [comment]
Hi @bemoregt, sorry for the delay. NAudio is a library aimed at analyzing _audio_ signals, so I suspect their FFT methods are all 1D only. Hopefully you can find an imaging library for .NET which supports 2D FFT!
